# ----------------------------
# Makefile Options
# ----------------------------

NAME = Calendar
DESCRIPTION = "Calendar for Ti84PlusCE"
ICON = icon.png
COMPRESSED = YES
COMPRESSED_MODE = zx7
ARCHIVED = YES
OUTPUT_MAP = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
